server:
  port: 8888
spring:
  application:
    name: Dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dept?useUnicode=true&characterEncoding=utf8
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1         # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0     # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启sql日志
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: top.shiyana.dept.entity